project:
  type: book
  output-dir: docs 

book:
  title: "Economics of Health Care"
  author: "Ian McCarthy"
  date: "6/21/2023"
  chapters:
    - preface.qmd
    - index.qmd
    - part: part1/insurance-0.qmd
      chapters: 
        - part1/insurance-1-1.qmd
        - part1/insurance-1-2.qmd
        - part1/insurance-2-1.qmd
        - part1/insurance-2-2.qmd
        - part1/insurance-3-1.qmd
        - part1/insurance-3-2.qmd
    - part: part2/physicians-0.qmd
      chapters:
        - part2/physicians-1-1.qmd
        - part2/physicians-2-1.qmd
        - part2/physicians-2-2.qmd
        - part2/physicians-3-1.qmd
        - part2/physicians-3-2.qmd
    - part: part3/hospitals-0.qmd
      chapters: 
        - part3/hospitals-1-1.qmd
        - part3/hospitals-1-2.qmd
        - part3/hospitals-2-1.qmd
        - part3/hospitals-2-2.qmd
        - part3/hospitals-3-1.qmd
        - part3/hospitals-3-2.qmd
    - part: part4/pharma-0.qmd
      chapters:
        - part4/pharma-1-1.qmd
        - part4/pharma-1-2.qmd
        - part4/pharma-1-3.qmd
        - part4/pharma-1-4.qmd

bibliography: BibTeX_Library.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreport
  epub:
    cover-image: cover.png