project:
  type: book
  output-dir: docs
  resources:
    - CNAME

execute:
  freeze: auto

book:
  title: "Economics of Health Care"
  author: "Ian McCarthy"
  date: today
  date-format: "MMMM YYYY"
  site-url: https://healthcare-markets.books.ianmccarthyecon.com
  repo-url: https://github.com/imccart/healthcare-markets-book
  reader-mode: true
  page-navigation: true
  sidebar:
    style: docked
    collapse-level: 1
  page-footer:
    left: "Ian McCarthy, Emory University"
    right: "Made with [Quarto](https://quarto.org/)"
  chapters:
    - preface.qmd
    - index.qmd
    - part: part1/insurance-0.qmd
      chapters: 
        - part1/insurance-1-1.qmd
        - part1/insurance-1-2.qmd
        - part1/insurance-2-1.qmd
        - part1/insurance-2-2.qmd
        - part1/insurance-3-1.qmd
        - part1/insurance-3-2.qmd
    - part: part2/physicians-0.qmd
      chapters:
        - part2/physicians-1-1.qmd
        - part2/physicians-2-1.qmd
        - part2/physicians-2-2.qmd
        - part2/physicians-3-1.qmd
        - part2/physicians-3-2.qmd
    - part: part3/hospitals-0.qmd
      chapters: 
        - part3/hospitals-1-1.qmd
        - part3/hospitals-1-2.qmd
        - part3/hospitals-2-1.qmd
        - part3/hospitals-2-2.qmd
        - part3/hospitals-3-1.qmd
        - part3/hospitals-3-2.qmd
    - part: part4/pharma-0.qmd
      chapters:
        - part4/pharma-1-1.qmd
        - part4/pharma-1-2.qmd
        - part4/pharma-1-3.qmd
        - part4/pharma-1-4.qmd

bibliography: ../../../administrative/templates/bibliography/BibTeX_Library.bib

format:
  html:
    theme:
      light: [cosmo, html/theme.scss]
      dark: [darkly, html/theme.scss, html/theme-dark.scss]
    toc: true
    toc-depth: 3
    number-depth: 3
  pdf:
    documentclass: scrreport
  epub:
    cover-image: cover.png