project:
  type: book

book:
  title: "Economics of Health Care"
  author: "Ian McCarthy"
  date: "3/28/2023"
  chapters:
    - preface.qmd
    - index.qmd
    - part: part1/insurance-0.qmd
      chapters: 
        - part1/insurance-1-1.qmd
        - part1/insurance-1-2.qmd
        - part1/insurance-2-1.qmd
        - part1/insurance-2-2.qmd

bibliography: BibTeX_Library.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreport
  epub:
    cover-image: cover.png