---
title: "Terminology"
---

```{r}
#| include: false
if (!require("pacman")) install.packages("pacman")
pacman::p_load(tidyverse, ggplot2, gganimate, gapminder, scales, hrbrthemes, OECD, here, png, gifski, magick, pdftools)
```

Historically, health insurance was relatively simple. You would pay a little bit every month to a health insurance company (sometimes little more than a union) in order to get access to health care should you need it. The insurance company would then pay for that care. The idea is that some patients will use relatively little care, generating excess revenue to the insurance company, while some other patients will use relatively more care, generating a loss. On average, if the insurance company priced their services appropriately, the excess revenue from the low-utilization patients will exceed the losses from the high-utilization patients. This is theoretically possible due to something called a **risk premium**, which we discuss in more detail in [Chapter -@sec-riskpremium]. 


But over time, especially as health care became more and more expensive, health insurance has become more and more complicated. At this point, even for health economists, understanding health insurance can be challenging. Much of the practical aspects of health insurance will remain unclear until you actually deal with certain frustrations personally --- such as providers that don't accept insurance (particularly common for dentists, optometrists, and mental health care in general) or the differences between in- and out-of-network providers, with associated differences in deductibles and out-of-pocket maximums. And if all of that sounds like gobbledegook, then you're in the right place! The purpose of this chapter is to lay out some basic health insurance terminology and how it all fits in the context of a health insurance plan.


## Managed Care?

One common term you might hear surrounding health insurance is @def-managedcare. "Management" in this context typically means that the insurer is trying to direct enrollees to certain providers over others, typically as a reflection of the prices they have negotiated with those providers. For example, assume there are two large hospital systems in a market, and that an insurer has negotiated lower payments with hospital A. Assume also that hospital A is pretty good --- sufficient quality, broad coverage of different conditions and treatments, etc. If an insurer could get its enrollees to go to hospital A instead of hospital B, then the insurer's costs would be lower (all else equal). So, the insurer might require that patients pay a little bit less out of pocket if they go to hospital A. This would be something like a Preferred Provider Organization (PPO), where the insurer will still pay for care provided at hospital B, but the patient might have to pay a larger share of that amount. Or, the insurer might refuse to pay at all of the patient goes to hospital B. This would be more like a Health Maintenance Organization (HMO), where the insurer will only pay for care at hospital A. Patients would have to pay the full amount for care if they go to hospital B. PPOs and HMOs are by far the most common forms of managed care insurance plans.

::: {#def-managedcare}

## Managed Care
A health insurance product that encompasses some attempt to manage utilization of health care among its enrollees, often via assigning providers (physicians, hospitals, etc.) into tiers separated based on pricing. 

:::

## Networks



## Cost-sharing

## Different Prices


